### PR TITLE
new ui dave S031 C028 

### PR DESCRIPTION
**Pull request by juzen2003**
# Re-open pull request #619 
# Update:
* More code styles clean-up in opus.css (these are missed from last Friday's update)

### CODE REVIEW

**Comment by juzen2003** [comment]
For further implementation/modification reference, move over Rob's last comments from #619 :
* When the spinner appears next to "General Constraints", it shows up between the text and the expand/collapse arrow. This means that the arrow moves over and then back again when the spinner appears and disappears. I think this is awkward-looking. The spinner should be to the right of the arrow. Ideally I think it would look nicest right-justified so it's sort of out of the way, but do what looks best.

* The behavior on the search page is now the same as the current version, but there's always been something that bothered me about the current version and now seems like a good time to fix it. The current process is:

  * Change the search
  * Put a results spinner and get the new results
  * Once the results count has been returned, query for a new menu and hint numbers and put spinners in those places
  * Once each of those has been returned, remove those spinners

The end result is that when you change the search, you see a single spinner for result count, even though the menu and the hint numbers are wrong and will be reloaded soon. The result count can take a long time to return, so it gives the impression those numbers are correct.

I think the right thing to do is put spinners on the menu and all the widgets with hints the instant the new result count is queried, rather than waiting for the individual API calls to be triggered. That way when you change the search, all the spinners will appear immediately, and then go out one by one as the API calls return.

* When you click on the "Cart" tab, it is displayed as black text on a blue background. However, when you (de)select one of the product types, the word "Cart" is changed to white on a blue background.

**Comment by juzen2003** [comment]
# Update
* rename #search_widgets to #op-search-widgets
* move .op-menu-text spinner to the right of down arrow next to "General Constraints"
* display .op-menu-text and #op-search-widgets spinners once #op-result-count spinner starts spinning
    * remove .op-menu-text spinner when getMenu finishes loading menu.html
    * remove #op-search-widgets spinner when getRangeEndpoints or getValidMults ajax return is done
* update coreui/css/style.css to have .navbar-dark .navbar-nav .nav-link.active:hover,
.navbar-dark .navbar-nav .nav-link.active:focus with color: #FFF (this is to remove our navbar text color conflict in line 4357 and 11239)

**Comment by rfrenchseti** [comment]
What is the point of changing “.op-menu-text .spinner” to “.op-menu-text.spinner”? I don’t know jQuery well but I thought the former was the normal was to select a child.

**Review by dstopp — CHANGES_REQUESTED** [review]
base.html line 85 - remove empty class
menu.html line 11 - i think you can condense to a single if block
style.css - you are changing a template file, not an opus file, so if we upgrade to a diff version we will lose your changes.  Suggestion that you make those changes in opus.css w/a note, if need be.  we should discuss.

**Comment by juzen2003** [comment]
# Update:
* base.html: remove empty class in line 85
* menu.html: condense to one if block
* move .navbar-dark .navbar-nav .nav-link.active:hover, .navbar-dark .navbar-nav .nav-link.active:focus with color: #FFF to opus.css 

# Note:
* jquery selector “.op-menu-text.spinner” is to select the element with both "op-menu-text" and "spinner" classes. To have spinner display at the right of down arrow, we have to move the spinner element out of "a" tag. And "op-menu-text" class is moved from the original "span" tag inside "a" tag to the "span" tag with "spinner" class. That's why jquery selector is changed to “.op-menu-text.spinner”.

**Comment by rfrenchseti** [comment]
So if .spinner is always on the same element as .op-menu-text is there a reason to include both?

**Comment by juzen2003** [comment]
.spinner is a shared class for multiple spinners (they are using the same background image), and the purpose of adding another class to the same element (like this case) or adding a class to parent container (like .op-total-size .spinner) is to customize the position of each spinner with margin, line height, etc to make it look better.

**Comment by rfrenchseti** [comment]
Oh never mind. I see what you're doing. Thanks.

**Pull request merged**
