### PR TITLE
fixes clicking on planet wasn't opening corresponding targets group

### PR DESCRIPTION
**Pull request by basilleaf**
Hello I noticed the targets were no longer opening when a planet is clicked so here is a fix for that.

### CODE REVIEW

**Comment by rfrenchseti** [comment]
Thanks! I hadn't noticed that. We have a major re-deploy happening in a few weeks so it will get added then.

**Comment by rfrenchseti** [comment]
Doesn't this change break the other switch cases? They use mult_id as well but now it won't be defined.

**Comment by basilleaf** [comment]
oops! ok i updated the PR I think

**Comment by rfrenchseti** [comment]
Integrated with new_import branch. Also swapped meaning of -/+ symbols, which were backwards.

**Pull request closed without merging**
