### PR TITLE
Generate html tags

### PR DESCRIPTION
**Pull request by fyellin**
First pass at generating html-formatted information.

### CODE REVIEW

**Comment by fyellin** [comment]
I'm confused.    I thought I generated this pull two days ago, but then it disappeared. Meanwhile, more stuff has been added.

**Comment by fyellin** [comment]
Ping?

**Comment by fyellin** [comment]
What is  juzen2003-input_validation_and_string_hints?  I thought this was
supposed to go into seti/opus-pds/log-analyzer.  Did I goof?

**Comment by rfrenchseti** [comment]
Sorry I must’ve been on the wrong branch when I merged. I’ll fix it in the morning.

**Comment by rfrenchseti** [comment]
I've done a full cross-merge of master and log_analyzer. The branches are now identical.

**Pull request merged**
